# These are supported funding model platforms

custom: ['https://venmo.com/Jeron-Osguthorpe', 'https://cash.app/$JeronOsguthorpe']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
Copyright © 2023 Jeron Osguthorpe
